s='Bye Bye Leazy'
print(s)
print(len(s))
print(s.upper())
print(s.lower())
print(s.swapcase())
print(s.title())
print(s.capitalize())
m='WelCOME tO Bangalore'
print(m)
print(m.upper())
print(m.lower())
print(m.swapcase())
print(m.capitalize())
print(m.title())
print(m.split())
print(m.split(' '))
print(m.split('O'))
print(m.split('O',1))
print(m.split('O',100))